config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :telefones
  resources :enderecos
  resources :contatos
  resources :tipos
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contato.rb
class Contato < ApplicationRecord
  belongs_to :tipo
end

app/models/endereco.rb
class Endereco < ApplicationRecord
  belongs_to :contato
end

app/models/telefone.rb
class Telefone < ApplicationRecord
  belongs_to :contato
end

app/models/tipo.rb
class Tipo < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contatos_controller.rb
class ContatosController < ApplicationController
  before_action :set_contato, only: %i[ show edit update destroy ]

  # GET /contatos or /contatos.json
  def index
    @contatos = Contato.all
  end

  # GET /contatos/1 or /contatos/1.json
  def show
  end

  # GET /contatos/new
  def new
    @contato = Contato.new
  end

  # GET /contatos/1/edit
  def edit
  end

  # POST /contatos or /contatos.json
  def create
    @contato = Contato.new(contato_params)

    respond_to do |format|
      if @contato.save
        format.html { redirect_to @contato, notice: "Contato was successfully created." }
        format.json { render :show, status: :created, location: @contato }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @contato.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contatos/1 or /contatos/1.json
  def update
    respond_to do |format|
      if @contato.update(contato_params)
        format.html { redirect_to @contato, notice: "Contato was successfully updated." }
        format.json { render :show, status: :ok, location: @contato }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @contato.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contatos/1 or /contatos/1.json
  def destroy
    @contato.destroy

    respond_to do |format|
      format.html { redirect_to contatos_path, status: :see_other, notice: "Contato was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contato
      @contato = Contato.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def contato_params
      params.require(:contato).permit(:nome, :email, :tipo_id, :rmk)
    end
end

app/controllers/enderecos_controller.rb
class EnderecosController < ApplicationController
  before_action :set_endereco, only: %i[ show edit update destroy ]

  # GET /enderecos or /enderecos.json
  def index
    @enderecos = Endereco.all
  end

  # GET /enderecos/1 or /enderecos/1.json
  def show
  end

  # GET /enderecos/new
  def new
    @endereco = Endereco.new
  end

  # GET /enderecos/1/edit
  def edit
  end

  # POST /enderecos or /enderecos.json
  def create
    @endereco = Endereco.new(endereco_params)

    respond_to do |format|
      if @endereco.save
        format.html { redirect_to @endereco, notice: "Endereco was successfully created." }
        format.json { render :show, status: :created, location: @endereco }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @endereco.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /enderecos/1 or /enderecos/1.json
  def update
    respond_to do |format|
      if @endereco.update(endereco_params)
        format.html { redirect_to @endereco, notice: "Endereco was successfully updated." }
        format.json { render :show, status: :ok, location: @endereco }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @endereco.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enderecos/1 or /enderecos/1.json
  def destroy
    @endereco.destroy

    respond_to do |format|
      format.html { redirect_to enderecos_path, status: :see_other, notice: "Endereco was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_endereco
      @endereco = Endereco.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def endereco_params
      params.require(:endereco).permit(:rua, :cidade, :estado, :contato_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/telefones_controller.rb
class TelefonesController < ApplicationController
  before_action :set_telefone, only: %i[ show edit update destroy ]

  # GET /telefones or /telefones.json
  def index
    @telefones = Telefone.all
  end

  # GET /telefones/1 or /telefones/1.json
  def show
  end

  # GET /telefones/new
  def new
    @telefone = Telefone.new
  end

  # GET /telefones/1/edit
  def edit
  end

  # POST /telefones or /telefones.json
  def create
    @telefone = Telefone.new(telefone_params)

    respond_to do |format|
      if @telefone.save
        format.html { redirect_to @telefone, notice: "Telefone was successfully created." }
        format.json { render :show, status: :created, location: @telefone }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @telefone.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /telefones/1 or /telefones/1.json
  def update
    respond_to do |format|
      if @telefone.update(telefone_params)
        format.html { redirect_to @telefone, notice: "Telefone was successfully updated." }
        format.json { render :show, status: :ok, location: @telefone }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @telefone.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /telefones/1 or /telefones/1.json
  def destroy
    @telefone.destroy

    respond_to do |format|
      format.html { redirect_to telefones_path, status: :see_other, notice: "Telefone was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_telefone
      @telefone = Telefone.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def telefone_params
      params.require(:telefone).permit(:telefone, :contato_id)
    end
end

app/controllers/tipos_controller.rb
class TiposController < ApplicationController
  before_action :set_tipo, only: %i[ show edit update destroy ]

  # GET /tipos or /tipos.json
  def index
    @tipos = Tipo.all
  end

  # GET /tipos/1 or /tipos/1.json
  def show
  end

  # GET /tipos/new
  def new
    @tipo = Tipo.new
  end

  # GET /tipos/1/edit
  def edit
  end

  # POST /tipos or /tipos.json
  def create
    @tipo = Tipo.new(tipo_params)

    respond_to do |format|
      if @tipo.save
        format.html { redirect_to @tipo, notice: "Tipo was successfully created." }
        format.json { render :show, status: :created, location: @tipo }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tipo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tipos/1 or /tipos/1.json
  def update
    respond_to do |format|
      if @tipo.update(tipo_params)
        format.html { redirect_to @tipo, notice: "Tipo was successfully updated." }
        format.json { render :show, status: :ok, location: @tipo }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tipo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tipos/1 or /tipos/1.json
  def destroy
    @tipo.destroy

    respond_to do |format|
      format.html { redirect_to tipos_path, status: :see_other, notice: "Tipo was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tipo
      @tipo = Tipo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tipo_params
      params.require(:tipo).permit(:descricao)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contatos_helper.rb
module ContatosHelper
end

app/helpers/enderecos_helper.rb
module EnderecosHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/telefones_helper.rb
module TelefonesHelper
end

app/helpers/tipos_helper.rb
module TiposHelper
end

app/views/contatos/_form.html.erb
<%= form_with(model: contato, local: true) do |form| %>
  <% if contato.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contato.errors.count, "error") %> prohibited this contato from being saved:</h2>

      <ul>
      <% contato.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :tipo_id %>
    <%= form.text_field :tipo_id %>
  </div>

  <div class="field">
    <%= form.label :rmk %>
    <%= form.text_area :rmk %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/contatos/edit.html.erb
<h1>Editing Contato</h1>

<%= render 'form', contato: @contato %>

<%= link_to 'Show', @contato %> |
<%= link_to 'Back', contatos_path %>

app/views/contatos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Contatos</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Email</th>
      <th>Tipo</th>
      <th>Rmk</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contatos.each do |contato| %>
      <tr>
        <td><%= contato.nome %></td>
        <td><%= contato.email %></td>
        <td><%= contato.tipo %></td>
        <td><%= contato.rmk %></td>
        <td><%= link_to 'Show', contato %></td>
        <td><%= link_to 'Edit', edit_contato_path(contato) %></td>
        <td><%= link_to 'Destroy', contato, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contato', new_contato_path %>

app/views/contatos/new.html.erb
<h1>New Contato</h1>

<%= render 'form', contato: @contato %>

<%= link_to 'Back', contatos_path %>

app/views/contatos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @contato.nome %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contato.email %>
</p>

<p>
  <strong>Tipo:</strong>
  <%= @contato.tipo %>
</p>

<p>
  <strong>Rmk:</strong>
  <%= @contato.rmk %>
</p>

<%= link_to 'Edit', edit_contato_path(@contato) %> |
<%= link_to 'Back', contatos_path %>

app/views/enderecos/_form.html.erb
<%= form_with(model: endereco, local: true) do |form| %>
  <% if endereco.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(endereco.errors.count, "error") %> prohibited this endereco from being saved:</h2>

      <ul>
      <% endereco.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :rua %>
    <%= form.text_field :rua %>
  </div>

  <div class="field">
    <%= form.label :cidade %>
    <%= form.text_field :cidade %>
  </div>

  <div class="field">
    <%= form.label :estado %>
    <%= form.text_field :estado %>
  </div>

  <div class="field">
    <%= form.label :contato_id %>
    <%= form.text_field :contato_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/enderecos/edit.html.erb
<h1>Editing Endereco</h1>

<%= render 'form', endereco: @endereco %>

<%= link_to 'Show', @endereco %> |
<%= link_to 'Back', enderecos_path %>

app/views/enderecos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Enderecos</h1>

<table>
  <thead>
    <tr>
      <th>Rua</th>
      <th>Cidade</th>
      <th>Estado</th>
      <th>Contato</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @enderecos.each do |endereco| %>
      <tr>
        <td><%= endereco.rua %></td>
        <td><%= endereco.cidade %></td>
        <td><%= endereco.estado %></td>
        <td><%= endereco.contato %></td>
        <td><%= link_to 'Show', endereco %></td>
        <td><%= link_to 'Edit', edit_endereco_path(endereco) %></td>
        <td><%= link_to 'Destroy', endereco, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Endereco', new_endereco_path %>

app/views/enderecos/new.html.erb
<h1>New Endereco</h1>

<%= render 'form', endereco: @endereco %>

<%= link_to 'Back', enderecos_path %>

app/views/enderecos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Rua:</strong>
  <%= @endereco.rua %>
</p>

<p>
  <strong>Cidade:</strong>
  <%= @endereco.cidade %>
</p>

<p>
  <strong>Estado:</strong>
  <%= @endereco.estado %>
</p>

<p>
  <strong>Contato:</strong>
  <%= @endereco.contato %>
</p>

<%= link_to 'Edit', edit_endereco_path(@endereco) %> |
<%= link_to 'Back', enderecos_path %>

app/views/home/index.html.erb
<h1>Seja bem vindo!</h1>

<ul>
    <li><%= link_to "Tipos", tipos_path %></li>
    <li><%= link_to "Contatos", contatos_path %></li>
    <li><%= link_to "Endereços", enderecos_path %></li>
    <li><%= link_to "Telefones", telefones_path %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Agenda</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/telefones/_form.html.erb
<%= form_with(model: telefone, local: true) do |form| %>
  <% if telefone.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(telefone.errors.count, "error") %> prohibited this telefone from being saved:</h2>

      <ul>
      <% telefone.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :telefone %>
    <%= form.text_field :telefone %>
  </div>

  <div class="field">
    <%= form.label :contato_id %>
    <%= form.text_field :contato_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/telefones/edit.html.erb
<h1>Editing Telefone</h1>

<%= render 'form', telefone: @telefone %>

<%= link_to 'Show', @telefone %> |
<%= link_to 'Back', telefones_path %>

app/views/telefones/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Telefones</h1>

<table>
  <thead>
    <tr>
      <th>Telefone</th>
      <th>Contato</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @telefones.each do |telefone| %>
      <tr>
        <td><%= telefone.telefone %></td>
        <td><%= telefone.contato %></td>
        <td><%= link_to 'Show', telefone %></td>
        <td><%= link_to 'Edit', edit_telefone_path(telefone) %></td>
        <td><%= link_to 'Destroy', telefone, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Telefone', new_telefone_path %>

app/views/telefones/new.html.erb
<h1>New Telefone</h1>

<%= render 'form', telefone: @telefone %>

<%= link_to 'Back', telefones_path %>

app/views/telefones/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Telefone:</strong>
  <%= @telefone.telefone %>
</p>

<p>
  <strong>Contato:</strong>
  <%= @telefone.contato %>
</p>

<%= link_to 'Edit', edit_telefone_path(@telefone) %> |
<%= link_to 'Back', telefones_path %>

app/views/tipos/_form.html.erb
<%= form_with(model: tipo, local: true) do |form| %>
  <% if tipo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tipo.errors.count, "error") %> prohibited this tipo from being saved:</h2>

      <ul>
      <% tipo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :descricao %>
    <%= form.text_field :descricao %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tipos/edit.html.erb
<h1>Editing Tipo</h1>

<%= render 'form', tipo: @tipo %>

<%= link_to 'Show', @tipo %> |
<%= link_to 'Back', tipos_path %>

app/views/tipos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tipos</h1>

<table>
  <thead>
    <tr>
      <th>Descricao</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tipos.each do |tipo| %>
      <tr>
        <td><%= tipo.descricao %></td>
        <td><%= link_to 'Show', tipo %></td>
        <td><%= link_to 'Edit', edit_tipo_path(tipo) %></td>
        <td><%= link_to 'Destroy', tipo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tipo', new_tipo_path %>

app/views/tipos/new.html.erb
<h1>New Tipo</h1>

<%= render 'form', tipo: @tipo %>

<%= link_to 'Back', tipos_path %>

app/views/tipos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Descricao:</strong>
  <%= @tipo.descricao %>
</p>

<%= link_to 'Edit', edit_tipo_path(@tipo) %> |
<%= link_to 'Back', tipos_path %>